export const MBTI_PERSONALITY = 'ENFP'
export const MBTI_PERSONALITY_NAME = '竞选者'
export const STAR_SIGN = '白羊座'
export const STAR_SIGN_NAME = 'Aries'
export const DATE_BIRTH = '1999'
export const PROFESSION = '网络工程'
export const LINK_MUSIC = '华语流行'
